# =================================================================================================#
# ROLE FUNCTION - Provision an 802.11 Connection                                                   #
# =================================================================================================#

- name: "PROVISION_NETWORKING/TASK_PROVISION/FUNC_WIFI/01 - Provision supplied Wireless Network"
  community.general.nmcli:
    conn_name: "{{ input_network.name }}"
    type: wifi
    state: present
    ifname: "{{ input_network.parent }}"
    ssid: "{{ input_network.wifi.ssid }}"
    wifi_sec:
      key-mgmt: "{{ input_network.wifi.security | default(omit) }}"
      psk: "{{ input_network.wifi.password | default(omit) }}"
    master: "{{ input_network.master | default(omit) }}"
    autoconnect: "{{ input_network.autoconnect | default(omit) }}"
    method4: "{{ (input_network.ipv4 is string) | ternary(input_network.ipv4, 'manual', 'none') }}"
    ip4: "{{ input_network.ipv4.address | default(omit) }}"
    gw4: "{{ input_network.ipv4.gateway | default(omit) }}"
    dns4: "{{ input_network.ipv4.dns | default(omit) }}"
    dns4_search: "{{ input_network.ipv4.search_domains | default(omit) }}"
    routes4: "{{ input_network.ipv4.routes | default(omit) }}"
    method6: "{{ (input_network.ipv6 is string) | ternary(input_network.ipv6, 'manual', 'none') }}"
    ip6: "{{ input_network.ipv6.address | default(omit) }}"
    gw6: "{{ input_network.ipv6.gateway | default(omit) }}"
    dns6: "{{ input_network.ipv6.dns | default(omit) }}"
    dns6_search: "{{ input_network.ipv6.search_domains | default(omit) }}"
    routes6: "{{ input_network.ipv6.routes | default(omit) }}"
  become: true
  register: wifi_build

- name: "PROVISION_NETWORKING/TASK_PROVISION/FUNC_WIFI/02 - Attach to bridge"
  ansible.builtin.command:
    cmd: "nmcli con modify {{ input_network.name }} master {{ input_network.master }} slave-type bridge"
  become: true
  changed_when: false
  when: (input_network.master is defined)  and (wifi_build.changed)
